### ISSUE TITLE
Not all the code uses LevelModel.Matrix

### ISSUE THREAD

**Issue by zluzunov** [HakuTeam/AlphaBomberman#1]
This version of the game has two problems - player 2 does not show in a resized level. The actual level and the level used by the game are different;
This may be due to the new LevelModel.Matrix - probably not all the code uses it. 
TO DO: search for the problem and fix it;
@HakuTeam/csharpadvanced

**Comment by dhtveso** [comment]
When i start game and set width to 17  and height to 21 all works fine

**Comment by dhtveso** [comment]
For second problem, about player, he hide under '#' because we put '#' on every even index. Matrix must be with odd width and height.

**Comment by dhtveso** [comment]
BombExplosion class generete new matrix all the time when we put Bomb to fix it put:
public static LevelModel Level;  
and make field to be equal to Level (var field = Level;)

**Comment by zluzunov** [comment]
Refactored the code. The new code works correctly;
