### ISSUE TITLE
What needs to be done.

### ISSUE THREAD

**Issue by badbutcher** [HakuTeam/AlphaBomberman#10]
- [1] When a player puts a bomb it must not disappear. DONE

- [2] A player must put one or more bombs without any problems. DONE

- [3] Bomb must explodes by itself after the given time. DONE

- [4] A bomb can set off other bombs.

What can be done but not necessary.

- [1] Show bomb explosion (may require bomb class refactor).

**Comment by zluzunov** [comment]
I can work on [1] tonight? Is it OK? Ready within 2 hours?
@badbutcher , @Plotso , @dhtveso

**Comment by dhtveso** [comment]
i will do 1st point in next few minute @zluzunov

**Comment by dhtveso** [comment]
Im done whit 1st problem.

**Comment by zluzunov** [comment]
[2] also fixed;
a4d98394beae29db6922077a353db1b55a88385c @badbutcher

**Comment by zluzunov** [comment]
[3] also done with 0e01cb85badfdf874e0048ff6ad597a41e842193

**Comment by zluzunov** [comment]
Moved to a new milestone #12
