### ISSUE TITLE
PlayerTwo Movement bug

### ISSUE THREAD

**Issue by dhtveso** [HakuTeam/AlphaBomberman#6]
PlayerTwo Movement must be fixed - now he move whit: 
'w' - left,
s - right,
a - up,
d - down
they need to be:
 w-up, d- right, s- down, a- left.  

@HakuTeam/csharpadvanced

**Comment by zluzunov** [comment]
@dhtveso 
Fixed with the latest commits; 
Rows and columns are now used in the names of variables - seems less error-prawn;
