### ISSUE TITLE
Player can put only 1 bomb.

### ISSUE THREAD

**Issue by badbutcher** [HakuTeam/AlphaBomberman#9]
If a player puts more than 1 bomb on the field they stop working.

**Comment by zluzunov** [comment]
Could be because both threads use the same list of bombs:
Parallel.Invoke(() => Bomb.CheckBombs(), () => Player.Move());

When a player changes the size of the list a new list is created or at least objects disappear or are not accessible for CheckBomb ? Just a guess.

**Comment by zluzunov** [comment]
Fixed with a4d98394beae29db6922077a353db1b55a88385c @badbutcher
